[package]
name = "bevy-wasm-fsharp-ref-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
bevy = { version = "0.15", default-features = false }
